### ISSUE TITLE
Default approval regex not respecting :+1:

### ISSUE THREAD

**Issue by davidcaseria** [reenhanced/gitreflow#182]
After using `git reflow setup`, the `constants` section in the `.gitconfig.reflow` file defaults the `approvalRegex` with `(?i-mx:lgtm|looks good to me|:\\+1:|:thumbsup:|:shipit:)`, however it does not respect PRs that have been approved by 👍  (`:+1:`).

**Comment by simonzhu24** [comment]
@davidcaseria I believe the expression should be:
```(?i-mx:lgtm|looks good to me|:\+1:|:thumbsup:|:shipit:)```

I can look more into this issue. In the meantime, could you please modify your `~/.gitconfig.reflow` to the expression above?

**Comment by simonzhu24** [comment]
@davidcaseria This should no longer be an issue when my pull request is approved! 
The issue was that when you call `to_s` on the regex: `(?i-mx:lgtm|looks good to me|:\+1:|:thumbsup:|:shipit:)`, it adds an extra `\` to the `:\+1:` expression for some reason. So when I was adding this to your `~/gitconfig.reflow` file, there was an extra `\` inserted.

**Comment by davidcaseria** [comment]
@simonzhu24: I changed the config be received the following error:
```
$ git reflow setup
fatal: bad config file line 9 in /Users/david/.gitconfig.reflow
```

**Comment by simonzhu24** [comment]
@davidcaseria: without seeing exactly what you have put on line 9, it is hard for me to debug your issue. The only change that you have to make in the config file from the original config is to remove a \ from the \\ expression.

**Comment by davidcaseria** [comment]
@simonzhu24: Here is the full .gitconfig.reflow:
```
[github]
        site = https://github.com
        endpoint = https://api.github.com
        oauth-token = REDACTED
[reflow]
        git-server = GitHub
[constants]
        minimumApprovals =
        approvalRegex = (?i-mx:lgtm|looks good to me|:\+1:|:thumbsup:|:shipit:)
```

**Comment by simonzhu24** [comment]
@davidcaseria Sorry for the late response, yesterday was very hectic. I believe that `approvalRegex` needs to have a complete regular expression as the value. It should be something like:

```
/(?i-mx:lgtm|looks good to me|:\+1:|:thumbsup:|:shipit:)/
```

Please let me know if this doesn't work for you.

**Comment by davidcaseria** [comment]
@simonzhu24 : No worries. That `approvalRegex ` still results in the same config error for any git commands.

**Comment by codenamev** [comment]
@davidcaseria what version of git are you using? also, can you do a sanity check for me `git reflow --version`

**Comment by davidcaseria** [comment]
```
$ git --version
git version 2.7.4 (Apple Git-66)
$ git reflow --version
git-reflow version 0.7.5
```
@codenamev: Should I upgrade to the latest versions?

**Comment by codenamev** [comment]
Ah, yes, we released `0.8.1` that adds quite a few fixes.  Please review [our latest release](https://articles.buildbettersoftware.com/new-git-reflow-release-new-refresh-command-and-api-stability-173681953097#.cketkw4ui) so you're aware of the latest changes to the underlying workflow.

If your problem goes away please close this or let me know so that I can :smile:

**Comment by davidcaseria** [comment]
@codenamev: It seems like 👍  is still not being respected in `v0.8.1`.

**Comment by simonzhu24** [comment]
The diff is still out and not merged yet, please wait for it to be merged.
