### ISSUE TITLE
Support for non-master branch

### ISSUE THREAD

**Issue by rarkins** [reenhanced/gitreflow#73]
The README refers to `master` branch explicitly and a quick search of the source code shows it mostly hardcoded. What would be the best way to support a permanently configured alternative base, e.g. 'develop'? e.g. supporting an environment variable `GITREFLOW_BASE` or something like that.

**Comment by sshilko** [comment]
wouls be nice, atm. u can (as a solution) append branch name at the end of commands (see #145) . only status cmd doesnt show updated status.

**Comment by simonzhu24** [comment]
@codenamev is this something we still want?

**Comment by rarkins** [comment]
FYI, I ended up switching to using `master` branch as default, so I no longer personally require this feature.

**Comment by sshilko** [comment]
i'm successfuly using 'git reflow deliver develop' w/o status command

**Comment by pboling** [comment]
Our base branch is `development`, and `master` is out production code, so we definitely need this feature @invoice2go.

**Comment by simonzhu24** [comment]
@codenamev @pboling I believe that Git Reflow currently supports this. With the recent changes to Git Reflow:

You can do:
1. git reflow start <branch_name> --base <base>
2. git reflow refresh --base <base>
3. git reflow review <base>
4. git reflow deliver <base>

If no base is specified, each command will default to Master, but when a <base> is specified, it will treat the <base> as the base branch instead.

**Comment by sshilko** [comment]
@simonzhu24 git reflow status is broken for non-master

**Comment by simonzhu24** [comment]
@sshilko I just tested it and it seems to be working fine for me? I pasted my terminal commands below. Can you give more information about what is broken or provide what you are seeing on the terminal?

Are you running the proper command? It is `git reflow status <branch_name> ` where branch_name is the base branch you want your PR to merge into. Otherwise, it is `master` by default.

```
Dev-Loaner-3s-MacBook-Pro:test ximengzhu$ git reflow start test_error
From https://github.com/simonzhu24/test
 * branch            new_test   -> FETCH_HEAD
Total 0 (delta 0), reused 0 (delta 0)
To https://github.com/simonzhu24/test.git
 * [new branch]      new_test -> test_error
Switched to a new branch 'test_error'
Dev-Loaner-3s-MacBook-Pro:test ximengzhu$ vim README.md
Dev-Loaner-3s-MacBook-Pro:test ximengzhu$ git commit -a -m "Test"
[test_error e362e30] Test
 1 file changed, 1 insertion(+), 1 deletion(-)
Dev-Loaner-3s-MacBook-Pro:test ximengzhu$ git reflow review 2lgtm
git fetch origin 2lgtm
From https://github.com/simonzhu24/test
 * branch            2lgtm      -> FETCH_HEAD

git push origin test_error
Counting objects: 3, done.
Writing objects: 100% (3/3), 262 bytes | 0 bytes/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To https://github.com/simonzhu24/test.git
   496cc0c..e362e30  test_error -> test_error


Review your PR:
--------
Title:
test_error

Body:


--------
Submit pull request? (Y)
Y
Successfully created pull request #40: test_error
Pull Request URL: https://github.com/simonzhu24/test/pull/40
Would you like to open it in your browser? Y

Dev-Loaner-3s-MacBook-Pro:test ximengzhu$ git reflow status 2lgtm
Here's the status of your review:
    branches:     simonzhu24:test_error -> simonzhu24:2lgtm
    number:       40
    reviewed by:
    url:          https://github.com/simonzhu24/test/pull/40

[notice] No one has reviewed your pull request.
Would you like to open it in your browser? N
```

**Comment by codenamev** [comment]
@sshilko the non-master support has not been officially released yet.  We have this planned for 0.8.0 as it is bundled with some potentially breaking changes that we'll need to outline.  If you would like to test this out, feel free to clone this repo and run `bundle exec rake install` to build and install the gem from source.

**Comment by sshilko** [comment]
Darwin zzz-air.local 15.2.0 Darwin Kernel Version 15.2.0: Fri Nov 13 19:56:56 PST 2015; root:xnu-3248.20.55~2/RELEASE_X86_64 x86_64

git-reflow version 0.7.5


```

# git reflow review develop                                                                                                       [10:19:59]
git fetch origin develop
From https://github.com/ggg/sss
 * branch            develop    -> FETCH_HEAD

git push origin test-1
Counting objects: 3, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 293 bytes | 0 bytes/s, done.
Total 3 (delta 2), reused 0 (delta 0)
To https://ccc@github.com/xxx/aa.git
   a116d84..038fc30  test-1 -> test-1


Review your PR:
--------
Title:
test-1

Body:


--------
Submit pull request? (Y)
Y
Successfully created pull request #64: test-1
Pull Request URL: https://github.com/zzz/ccc/pull/64
Would you like to open it in your browser? n

sshilko•vive/headr_php/test(test-1)» git reflow status                                                                                                               [10:20:25]

[notice] No pull request exists for test-1 -> master
[notice] Run 'git reflow review master' to start the review process

```

git feflow status does not see the pull requests for me in 0.7.5

**Comment by sshilko** [comment]
@simonzhu24 i tested it again and works for me too now, sorry for trouble

**Comment by codenamev** [comment]
Fixed in v0.8.0 with 3b44510b7042f7aa6db76248aa52123145732c0a.

**Comment by pboling** [comment]
@codenamev @simonzhu24 This is still broken.  `deliver` is not working, because it doesn't accept a `--base` option, and even if it did it wouldn't pass it through to `GitReflow.deliver`.  `GitReflow.deliver` does support `options[:base]`, but since it can't ever get it, it always defaults to `master`.

https://github.com/reenhanced/gitreflow/blob/master/lib/git_reflow/commands/deliver.rb#L8
